---
always_allow_html: yes
title: "ArtEco"
output:
  html_document:
    fig_width: 7
    number_sections: no
    self_contained: yes
  pdf_document: default
  word_document: default
editor_options: 
  chunk_output_type: console
---
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
```{css css_Styles, echo=FALSE}
 <style> 
    @media {
  body {
    width: 860px;
    margin: auto;
} 
}
@page {
  size: Letter;
  width: 860px;
  height: 1050px;
  margin: auto;
}

body { /* Normal  */
  font-size: 14px;
  font-family: "Cambria", sans-serif;
  line-height: 15px ;
  text-align: justify;
}
td {  /* Table  */
  font-size: 10px;
  font-family: "Cambria", sans-serif;
  line-height: 12px;
  text-align: center;
}
table {
  padding-left: 5px;
  padding-right: 5px;
  min-width: 75%;
  text-align:center;
  margin: 0 auto;
  }
.title {
  font-size: 12px;
  font-family: "Cambria", sans-serif;
  font-weight: bold;
  font-variant: small-caps;
  text-align: left;
}
h1 { /* Header 1 */
  font-size: 16px;
  font-family: "Cambria", sans-serif;
  font-weight: bold;
  font-variant: small-caps;
  text-align: center;
}
h2 { /* Header 2 */
  font-size: 16px;
  font-family: "Cambria", sans-serif;
  font-variant: small-caps;
  font-weight: bold;
  text-align: center;
}
h3 { /* Header 3 */
  font-size: 14px;
  font-family: "Cambria", sans-serif;
  font-variant: small-caps;
  font-weight: bold;
  text-align: left;
}
h4 { /* Header 4 */
  font-size: 13px;
  font-family: "Cambria", sans-serif;
  font-variant: small-caps;
  text-align: left;
}
</style>
```
```{css css_Setup, eval=TRUE, echo=FALSE}
 <script type="text/x-mathjax-config"> 
    MathJax.Hub.Config({ 
        "HTML-CSS": { scale: 100, linebreaks: { automatic: false } }, 
        TeX: { equationNumbers: { autoNumber: "AMS" } }});
</script>
```
</head>
<body>
<div class="header"  style="width:  775px; padding: 85px;">
<h1>Open-Ready [Self-Contained]<br></h1>
<h2>Diversity and Impact Measurement<br></h2>
<h3>Xavier Lemyre</h3>
<h4>October 1, 2020</h4>
</div><br>
<P style="page-break-after: always">
<div style="border: 3px solid Gray; border-style: ridge; width: 775px; height: 1000px; padding: 85px; page-break-after: always">

<br>

</div><br>
<div style="border: 3px solid Gray; border-style: ridge; width: 775px; height: 1000px; padding: 85px; page-break-after: always">

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

<iframe
    width="600"
    height="300"
    src="">
</iframe>
<br>

```{r}
is.R() #? #utf8
```

```{r knitr_setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
#Packages used in this file:
library(knitr)

```

</div><br>
<div style="border: 3px solid Gray; border-style: ridge; width: 775px; height: 1000px; padding: 85px; page-break-after: always">


# Diversity and Impact Measurement


```{r Environment, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
rm(list = ls())
I <- 1000
M <- data.frame(W = c(1),
                X = c((1:I)/I),
                Y = c(1/2),
                Z = c(0))
L <- length(M$X)
XL <- M$X * L
z <- (-1)^(M$X*I)
M.XL <- rbind(head(XL),tail(XL))
M.XL
plot(x = M$X, y = M$Y*z)
```

<iframe
    width="150"
    height="150"
    src="">
</iframe>



</div><br>
<div style="border: 3px solid Gray; border-style: ridge; width: 775px; height: 1000px; padding: 85px; page-break-after: always">


# References
```{r References, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
Ref <- matrix("", ncol = 5, nrow = 1, byrow = TRUE)
#Ref <- c("", "", "", "", "")
colnames(Ref) <- c("Author", "Year", "Title","Editors","pages")
Ref <- rbind(Ref,c("", "", "", "", ""))
Ref <- rbind(Ref,c("", "", "", "", ""))
Ref <- rbind(Ref,c("", "", "", "", ""))
Ref <- rbind(Ref,c("", "", "", "", ""))
Ref <- rbind(Ref,c("", "", "", "", ""))
Ref <- rbind(Ref,c("", "", "", "", ""))
# Ref <- rbind(Ref,c("", "", "", "",""))``
REFERENCES <- as.data.frame(Ref, row.names = NULL)
REFERENCES
```

</div><br>

</body>
</html>
